### ISSUE TITLE
Creating a new Project or a new Task

### ISSUE THREAD

**Issue by mojcas** [CodeCatz/TrackCat#202]
When creating a new Project or a new Task, the Owner pulldown list still has UserProfile object

**Comment by anuschka** [comment]
I believe this is ok @mojcas since the UperProfile object returns user.username due to unicode definition.

**Comment by mojcas** [comment]
I don't think so, more like a bug.. check http://localhost:8000/project/new/ and try to select Owner..same in http://localhost:8000/tasks/new/.. this should show the username rather instead of "UserProfile object" text in the pulldown menu..

**Comment by ialja** [comment]
This has been fixed when @anuschka added the `__unicode__` method to the Models. Make sure the branch you're working on is synced with the upstream master.

**Comment by mojcas** [comment]
it is not fixed, I'm on a last synced code..check http://localhost:8000/project/new/ and try to select Owner..same in http://localhost:8000/tasks/new/.. this should show the username rather instead of "UserProfile object" text in the pulldown menu..

**Comment by ialja** [comment]
It is fixed. Make sure everything is synced, migrations have been run etc. 

![screen shot 2015-02-26 at 15 16 35](https://cloud.githubusercontent.com/assets/1607407/6393472/9b117ec0-bdca-11e4-88db-df132803aea8.png)

**Comment by mojcas** [comment]
Strange. My master is synced, I have deleted the database and run migrations again, and still I don't see it...
![newproject](https://cloud.githubusercontent.com/assets/9574778/6417030/f7e051ea-beaa-11e4-90a7-da1c56aaef87.png)

**Comment by anuschka** [comment]
@mojcas It appears like you have the old model without unicode. Strange indeed :confused:

**Comment by mojcas** [comment]
So I am the only one? I have rebuilt the database and my master is synced.. weird :)

**Comment by anuschka** [comment]
I am sure you did ... but ... did you run ./manage.py makemigrations

**Comment by mojcas** [comment]
(myvenv) C:\work\TrackCat>python manage.py makemigrations
No changes detected

**Comment by anuschka** [comment]
Maybe a far fetch ... but ... is it something to do with displaying unicode on windows console?

**Comment by gandalfar** [comment]
It's not migrations. Look into models.py if you have `__unicode__` string

**Comment by mojcas** [comment]
Yes. I have it.. My master is synced with CodeCatz master.

**Comment by ialja** [comment]
@mojcas Are you by any chance using Python 3? (You shouldn't.) Also, a closed issues isn't really the best place for such questions.

**Comment by mojcas** [comment]
I am not using Python 3:

(myvenv) C:\work\TrackCat>python
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Weirdest thing that it works perfectly in Dyango admin, but not on the TrackCat site on adding a project or task objects.

 It if is only me, having this issue, that's okay (keep issue closed), but if there are others, you may want to reopen it...

**Comment by ialja** [comment]
You are using Python 3 (we agreed to stay on 2.7) and that's what's causing the problem: http://stackoverflow.com/questions/18588046/django-unicode-method-doesnt-work 

Issue closed.

**Comment by mojcas** [comment]
Ah ok, thanks Alja!
